# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChGK_gui_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PIL import ImageTk, Image
import tkinter as tk

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 682)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_frame = QtWidgets.QFrame(self.centralwidget)
        self.start_frame.setGeometry(QtCore.QRect(10, 7, 701, 64))
        self.start_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_frame.setObjectName("start_frame")
        self.start_btn = QtWidgets.QPushButton(self.start_frame)
        self.start_btn.setGeometry(QtCore.QRect(500, 10, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.start_btn.setFont(font)
        self.start_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.start_btn.setObjectName("start_btn")
        self.url_label = QtWidgets.QLabel(self.start_frame)
        self.url_label.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.url_label.setFont(font)
        self.url_label.setObjectName("url_label")
        self.url_lineEdit = QtWidgets.QLineEdit(self.start_frame)
        self.url_lineEdit.setGeometry(QtCore.QRect(120, 10, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.url_lineEdit.setFont(font)
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.game_header_label = QtWidgets.QLabel(self.start_frame)
        self.game_header_label.setGeometry(QtCore.QRect(10, 34, 691, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.game_header_label.setFont(font)
        self.game_header_label.setText("")
        self.game_header_label.setObjectName("game_header_label")
        self.game_header_label.setWordWrap(True)

        font = QtGui.QFont()
        font.setPointSize(10)

        self.question_frame = QtWidgets.QFrame(self.centralwidget)
        self.question_frame.setGeometry(QtCore.QRect(10, 80, 491, 201))
        self.question_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.question_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.question_frame.setObjectName("question_frame")
        self.question_textEdit = QtWidgets.QTextEdit(self.question_frame)
        self.question_textEdit.setGeometry(QtCore.QRect(10, 0, 481, 191))
        self.question_textEdit.setObjectName("question_textEdit")
        self.question_textEdit.setFont(font)
        self.answer_frame = QtWidgets.QFrame(self.centralwidget)
        self.answer_frame.setGeometry(QtCore.QRect(10, 280, 491, 161))
        self.answer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.answer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.answer_frame.setObjectName("answer_frame")
        self.answer_textEdit = QtWidgets.QTextEdit(self.answer_frame)
        self.answer_textEdit.setGeometry(QtCore.QRect(10, 0, 481, 161))
        self.answer_textEdit.setObjectName("answer_textEdit")
        self.answer_textEdit.setFont(font)

        self.result_frame = QtWidgets.QFrame(self.centralwidget)
        self.result_frame.setGeometry(QtCore.QRect(10, 450, 691, 211))
        self.result_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.result_frame.setObjectName("result_frame")
        self.result_label = QtWidgets.QLabel(self.result_frame)
        self.result_label.setGeometry(QtCore.QRect(0, 0, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")
        self.results_table = QtWidgets.QTableWidget(self.result_frame)
        self.results_table.setGeometry(QtCore.QRect(10, 30, 481, 141))
        self.results_table.setObjectName("results_table")
        self.show_results_label = QtWidgets.QLabel(self.result_frame)
        self.show_results_label.setGeometry(QtCore.QRect(500, 30, 191, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_results_label.setFont(font)
        self.show_results_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.show_results_label.setObjectName("show_results_label")

        self.control_frame = QtWidgets.QFrame(self.centralwidget)
        self.control_frame.setGeometry(QtCore.QRect(510, 80, 201, 361))
        self.control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_frame.setObjectName("control_frame")
        self.previous_btn = QtWidgets.QPushButton(self.control_frame)
        self.previous_btn.setGeometry(QtCore.QRect(0, 0, 61, 41))
        font = QtGui.QFont()
        font.setKerning(True)
        self.previous_btn.setFont(font)
        self.previous_btn.setText("")
        icon = QtGui.QIcon.fromTheme("c:\\Users\\Polina.DESKTOP-UGBOPLJ\\PycharmProjects\\previous.png")
        self.previous_btn.setIcon(icon)
        self.previous_btn.setIconSize(QtCore.QSize(30, 16))
        self.previous_btn.setObjectName("previous_btn")
        self.pause_btn = QtWidgets.QPushButton(self.control_frame)
        self.pause_btn.setGeometry(QtCore.QRect(70, 0, 61, 41))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pause_btn.setFont(font)
        self.pause_btn.setText("")
        icon = QtGui.QIcon.fromTheme("c:\\Users\\Polina.DESKTOP-UGBOPLJ\\PycharmProjects\\pause.png")
        self.pause_btn.setIcon(icon)
        self.pause_btn.setIconSize(QtCore.QSize(30, 20))
        self.pause_btn.setObjectName("pause_btn")
        self.next_btn = QtWidgets.QPushButton(self.control_frame)
        self.next_btn.setGeometry(QtCore.QRect(140, 0, 61, 41))
        font = QtGui.QFont()
        font.setKerning(True)
        self.next_btn.setFont(font)
        self.next_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Program Files (x86)/Qt Designer"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../next.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.next_btn.setIcon(icon)
        self.next_btn.setIconSize(QtCore.QSize(30, 16))
        self.next_btn.setObjectName("next_btn")
        self.show_answer_btn = QtWidgets.QPushButton(self.control_frame)
        self.show_answer_btn.setGeometry(QtCore.QRect(0, 200, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_answer_btn.setFont(font)
        self.show_answer_btn.setObjectName("show_answer_btn")
        self.timer_label = QtWidgets.QLabel(self.control_frame)
        self.timer_label.setGeometry(QtCore.QRect(50, 76, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(53)
        font.setBold(False)
        font.setWeight(50)
        self.timer_label.setFont(font)
        self.timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.timer_label.setObjectName("timer_label")
        self.is_answered_checkBox = QtWidgets.QCheckBox(self.control_frame)
        self.is_answered_checkBox.setGeometry(QtCore.QRect(0, 240, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.is_answered_checkBox.setFont(font)
        self.is_answered_checkBox.setObjectName("is_answered_checkBox")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChGK"))
        self.start_btn.setText(_translate("MainWindow", "Начать"))
        self.url_label.setText(_translate("MainWindow", "Вставьте ссылку: "))
        self.result_label.setText(_translate("MainWindow", "Результаты"))
        self.show_answer_btn.setText(_translate("MainWindow", "Показать ответ"))
        # self.show_results_label.setText(_translate("MainWindow", "Всего ответов:"))
        # self.timer_label.setText(_translate("MainWindow", "60"))
        self.is_answered_checkBox.setText(_translate("MainWindow", "Я ответил правильно"))


# class Razdatka_Window():
#     def __init__(self):
#         self.root = tk.Tk()
#         self.panel = tk.Label(self.root)
#         self.url=''
#
#     def create_window(self):
#         self.root.title = 'Razdatka'
#         self.panel.configure(text='test2')
#         self.panel.pack()
#         self.root.mainloop()
#
#     def hide(self):
#         self.root.withdraw()
#
#     def quit(self):
#         self.root.destroy()
# #         TODO в момент закрытия основного приложения закрывать вспомогательное
#
#     def show(self):
#         self.root.deiconify()


