# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChGK_gui_1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_frame = QtWidgets.QFrame(self.centralwidget)
        self.start_frame.setGeometry(QtCore.QRect(10, 10, 621, 41))
        self.start_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.start_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.start_frame.setObjectName("start_frame")
        self.start_btn = QtWidgets.QPushButton(self.start_frame)
        self.start_btn.setGeometry(QtCore.QRect(500, 10, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.start_btn.setFont(font)
        self.start_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.start_btn.setObjectName("start_btn")
        self.url_label = QtWidgets.QLabel(self.start_frame)
        self.url_label.setGeometry(QtCore.QRect(10, 10, 101, 20))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.url_label.setFont(font)
        self.url_label.setObjectName("url_label")
        self.url_lineEdit = QtWidgets.QLineEdit(self.start_frame)
        self.url_lineEdit.setGeometry(QtCore.QRect(120, 10, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.url_lineEdit.setFont(font)
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.question_frame = QtWidgets.QFrame(self.centralwidget)
        self.question_frame.setGeometry(QtCore.QRect(10, 60, 491, 221))
        self.question_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.question_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.question_frame.setObjectName("question_frame")
        self.question_textEdit = QtWidgets.QTextEdit(self.question_frame)
        self.question_textEdit.setGeometry(QtCore.QRect(10, 30, 481, 191))
        self.question_textEdit.setObjectName("question_textEdit")
        self.game_header_label = QtWidgets.QLabel(self.question_frame)
        self.game_header_label.setGeometry(QtCore.QRect(10, 0, 481, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.game_header_label.setFont(font)
        self.game_header_label.setText("")
        self.game_header_label.setObjectName("game_header_label")
        self.answer_frame = QtWidgets.QFrame(self.centralwidget)
        self.answer_frame.setGeometry(QtCore.QRect(10, 290, 491, 151))
        self.answer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.answer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.answer_frame.setObjectName("answer_frame")
        self.answer_textEdit = QtWidgets.QTextEdit(self.answer_frame)
        self.answer_textEdit.setGeometry(QtCore.QRect(10, 0, 481, 121))
        self.answer_textEdit.setObjectName("answer_textEdit")
        self.is_answered_checkBox = QtWidgets.QCheckBox(self.answer_frame)
        self.is_answered_checkBox.setGeometry(QtCore.QRect(10, 130, 181, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.is_answered_checkBox.setFont(font)
        self.is_answered_checkBox.setObjectName("is_answered_checkBox")
        self.control_frame = QtWidgets.QFrame(self.centralwidget)
        self.control_frame.setGeometry(QtCore.QRect(10, 450, 611, 101))
        self.control_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_frame.setObjectName("control_frame")
        self.minute_progressBar = QtWidgets.QProgressBar(self.control_frame)
        self.minute_progressBar.setGeometry(QtCore.QRect(240, 20, 271, 23))
        self.minute_progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.minute_progressBar.setAutoFillBackground(False)
        self.minute_progressBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.minute_progressBar.setProperty("value", 24)
        self.minute_progressBar.setObjectName("minute_progressBar")
        self.previous_btn = QtWidgets.QPushButton(self.control_frame)
        self.previous_btn.setGeometry(QtCore.QRect(10, 50, 61, 41))
        font = QtGui.QFont()
        font.setKerning(True)
        self.previous_btn.setFont(font)
        self.previous_btn.setText("")
        icon = QtGui.QIcon.fromTheme("c:\\Users\\Polina.DESKTOP-UGBOPLJ\\PycharmProjects\\previous.png")
        self.previous_btn.setIcon(icon)
        self.previous_btn.setIconSize(QtCore.QSize(30, 16))
        self.previous_btn.setObjectName("previous_btn")
        self.previous_btn.setEnabled(False)
        self.pause_btn = QtWidgets.QPushButton(self.control_frame)
        self.pause_btn.setGeometry(QtCore.QRect(80, 50, 61, 41))
        font = QtGui.QFont()
        font.setKerning(True)
        self.pause_btn.setFont(font)
        self.pause_btn.setText("")
        icon = QtGui.QIcon.fromTheme("c:\\Users\\Polina.DESKTOP-UGBOPLJ\\PycharmProjects\\pause.png")
        self.pause_btn.setIcon(icon)
        self.pause_btn.setIconSize(QtCore.QSize(30, 20))
        self.pause_btn.setObjectName("pause_btn")
        self.next_btn = QtWidgets.QPushButton(self.control_frame)
        self.next_btn.setGeometry(QtCore.QRect(150, 50, 61, 41))
        font = QtGui.QFont()
        font.setKerning(True)
        self.next_btn.setFont(font)
        self.next_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Program Files (x86)/Qt Designer"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../next.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.next_btn.setIcon(icon)
        self.next_btn.setIconSize(QtCore.QSize(30, 16))
        self.next_btn.setObjectName("next_btn")
        self.show_answer_btn = QtWidgets.QPushButton(self.control_frame)
        self.show_answer_btn.setGeometry(QtCore.QRect(10, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.show_answer_btn.setFont(font)
        self.show_answer_btn.setText("Показать ответ")
        self.show_answer_btn.setObjectName("show_answer_btn")
        self.timer_label = QtWidgets.QLabel(self.control_frame)
        self.timer_label.setGeometry(QtCore.QRect(520, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.timer_label.setFont(font)
        self.timer_label.setText("")
        self.timer_label.setObjectName("timer_label")
        self.minute_slider = QtWidgets.QSlider(self.control_frame)
        self.minute_slider.setGeometry(QtCore.QRect(240, 60, 241, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minute_slider.setFont(font)
        self.minute_slider.setOrientation(QtCore.Qt.Horizontal)
        self.minute_slider.setObjectName("minute_slider")
        self.result_frame = QtWidgets.QFrame(self.centralwidget)
        self.result_frame.setGeometry(QtCore.QRect(510, 60, 160, 400))
        self.result_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.result_frame.setObjectName("result_frame")
        self.result_label = QtWidgets.QLabel(self.result_frame)
        self.result_label.setGeometry(QtCore.QRect(0, 0, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.result_label.setFont(font)
        self.result_label.setObjectName("result_label")

        self.results_table = QtWidgets.QTableWidget(self.result_frame)
        self.results_table.setGeometry(QtCore.QRect(0, 30, 142, 321))
        self.results_table.setObjectName("results_table")
        self.results_table.setEnabled(False)

        # self.results_tableView = QtWidgets.QTableView(self.result_frame)
        # self.results_tableView.setGeometry(QtCore.QRect(0, 30, 142, 321))
        # self.results_tableView.setObjectName("results_tableView")
        # self.results_tableView.setEnabled(False)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 637, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChGK"))
        self.start_btn.setText(_translate("MainWindow", "Начать"))
        self.url_label.setText(_translate("MainWindow", "Вставьте ссылку: "))
        self.is_answered_checkBox.setText(_translate("MainWindow", "Я ответил правильно"))
        self.result_label.setText(_translate("MainWindow", "Результаты"))

